name: Backend Test

on:
  push:
    branches: [development, master, v*.x]
    tags:
      - v**
  pull_request:
  
jobs:
  build_backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and run tests
      run: docker-compose up -d
        
      
